# Generated by Django 2.1.3 on 2019-05-24 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('temperature', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='temperature',
            name='pre_change_date',
            field=models.DateTimeField(),
        ),
    ]
