# Generated by Django 2.1.3 on 2019-05-31 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('temperature', '0003_temperature_default_target_temp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='temperature',
            name='rate_h',
            field=models.FloatField(default=1.5),
        ),
        migrations.AlterField(
            model_name='temperature',
            name='rate_l',
            field=models.FloatField(default=0.5),
        ),
        migrations.AlterField(
            model_name='temperature',
            name='rate_m',
            field=models.FloatField(default=1),
        ),
    ]
