# Generated by Django 2.1.3 on 2019-05-31 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('temperature', '0004_auto_20190531_2103'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='temperature',
            name='pre_change_date',
        ),
        migrations.RemoveField(
            model_name='temperature',
            name='target_temp',
        ),
        migrations.AddField(
            model_name='temperature',
            name='mode',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='temperature',
            name='default_target_temp',
            field=models.FloatField(default=25.0),
        ),
        migrations.AlterField(
            model_name='temperature',
            name='rate_default',
            field=models.FloatField(default=1.0),
        ),
        migrations.AlterField(
            model_name='temperature',
            name='temp',
            field=models.FloatField(default=25.0),
        ),
    ]
