# Generated by Django 2.1.3 on 2019-06-01 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('temperature', '0005_auto_20190531_2332'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='temperature',
            name='mode',
        ),
    ]
