# Generated by Django 2.1.3 on 2019-05-20 16:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('times_of_on_and_off', models.IntegerField(default=0)),
                ('serving_duration', models.IntegerField(default=0)),
                ('total_Fee', models.FloatField(default=0)),
                ('times_of_dispatch', models.IntegerField(default=0)),
                ('number_of_RDR', models.IntegerField(default=0)),
                ('times_of_changeTemp', models.IntegerField(default=0)),
                ('times_of_changeFanSpeed', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='RequestDetailRecords',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fan_speed', models.IntegerField()),
                ('fee_rate', models.FloatField()),
                ('fee', models.FloatField()),
                ('request_time', models.DateField()),
                ('request_duration', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('fan_speed', models.IntegerField()),
                ('fee_rate', models.FloatField()),
                ('fee', models.FloatField()),
                ('room_id', models.IntegerField(primary_key=True, serialize=False)),
                ('state_working', models.BooleanField()),
                ('state_serving', models.BooleanField()),
                ('state_waiting', models.BooleanField()),
                ('current_temp', models.IntegerField()),
                ('target_temp', models.IntegerField()),
                ('serving_duration', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WorkingParameter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.IntegerField()),
                ('Temp_highLimit', models.IntegerField()),
                ('Temp_lowLimit', models.IntegerField()),
                ('default_TargetTemp', models.IntegerField()),
                ('FeeRate_H', models.FloatField()),
                ('FeeRate_M', models.FloatField()),
                ('FeeRate_L', models.FloatField()),
            ],
        ),
        migrations.AddField(
            model_name='requestdetailrecords',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.Room'),
        ),
        migrations.AddField(
            model_name='report',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.Room'),
        ),
    ]
