# Generated by Django 2.1.3 on 2019-05-25 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestdetailrecords',
            name='fan_speed',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='requestdetailrecords',
            name='fee',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='requestdetailrecords',
            name='fee_rate',
            field=models.FloatField(default=1),
        ),
        migrations.AlterField(
            model_name='room',
            name='current_temp',
            field=models.IntegerField(default=25),
        ),
        migrations.AlterField(
            model_name='room',
            name='fan_speed',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='room',
            name='fee',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='room',
            name='fee_rate',
            field=models.FloatField(default=1),
        ),
        migrations.AlterField(
            model_name='room',
            name='serving_duration',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='room',
            name='state_serving',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='room',
            name='state_waiting',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='room',
            name='state_working',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='room',
            name='target_temp',
            field=models.IntegerField(default=25),
        ),
    ]
