# Generated by Django 2.1.3 on 2019-06-03 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0003_auto_20190602_1150'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='init_cur_temp',
            field=models.FloatField(default=25),
        ),
    ]
