# Generated by Django 2.1.3 on 2019-06-04 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0004_room_init_cur_temp'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='for_timer_weight',
            field=models.FloatField(default=0),
        ),
    ]
